Route3_Text_TunnelFromCeruleanTiring::
    .string "Whew… I better take a rest…\n"
    .string "Groan…\p"
    .string "That tunnel from CERULEAN takes a\n"
    .string "lot out of you!$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "Ich habe dich im Vertania Wald gesehen!$"

Route3_Text_ColtonDefeat::
    .string "Du hast mich schon wieder besiegt!$"

Route3_Text_ColtonPostBattle::
    .string "Es gibt noch andere Arten von POKéMON\n"
    .string "als die, welche du im Wald fangen konntest.$"

Route3_Text_BenIntro::
    .string "Hi!\n"
    .string "Warst du auch bei Professor Eich?\p"
    .string "Ich habe von ihm ein starkes Pokemon\n"
    .string "erhalten und habe ein gutes Team!$"

Route3_Text_BenDefeat::
    .string "Niemals! Bisasam ist das stärkste.$"

Route3_Text_BenPostBattle::
    .string "Im Pokemon Center werden deine\n"
    .string "Pokemon nach dem 6ten aufbewahrt.\p"
    .string "Die PC Box kann bis zu 30\n"
    .string "POKéMON beinhalten.$"

Route3_Text_JaniceIntro::
    .string "Excuse me!\n"
    .string "You looked at me, didn't you?$"

Route3_Text_JaniceDefeat::
    .string "You're mean!$"

Route3_Text_JanicePostBattle::
    .string "You shouldn't be staring if you\n"
    .string "don't want to battle!$"

Route3_Text_GregIntro::
    .string "Are you a TRAINER?\n"
    .string "Let's get with it right away!$"

Route3_Text_GregDefeat::
    .string "If I had new POKéMON, I would've\n"
    .string "won!$"

Route3_Text_GregPostBattle::
    .string "If a POKéMON BOX on the PC gets\n"
    .string "full, just switch to another BOX.$"

Route3_Text_SallyIntro::
    .string "That look you gave me…\n"
    .string "It's so intriguing!$"

Route3_Text_SallyDefeat::
    .string "Be nice!$"

Route3_Text_SallyPostBattle::
    .string "You can avoid battles by not\n"
    .string "letting TRAINERS see you.$"

Route3_Text_CalvinIntro::
    .string "Hey! You're not wearing shorts!\n"
    .string "What's wrong with you?$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
    .string "I always wear shorts, even in\n"
    .string "winter. That's my policy.$"

Route3_Text_JamesIntro::
    .string "I'll battle you with the POKéMON\n"
    .string "I just caught.$"

Route3_Text_JamesDefeat::
    .string "Done like dinner!$"

Route3_Text_JamesPostBattle::
    .string "Trained POKéMON are stronger than\n"
    .string "the wild ones.$"

Route3_Text_RobinIntro::
    .string "Eek!\n"
    .string "Did you touch me?$"

Route3_Text_RobinDefeat::
    .string "That's it?$"

Route3_Text_RobinPostBattle::
    .string "ROUTE 4 is at the foot of\n"
    .string "MT. MOON.$"

Route3_Text_RouteSign::
    .string "ROUTE 3\n"
    .string "MT. MOON AHEAD$"
Route3_Text_Guy::
    .string "I've heard you can find SLUGMA\n"  
    .string "in the grass here.\l"  
    .string "It's a JOHTO POKéMON.\p"  
    .string "Since KANTO is so close to JOHTO,\n"
    .string "I'd expect that POKéMON often\l"  
    .string "migrate here.$"  
