Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "Nimm diesen Trank.$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Wir verkaufen auch Pokebälle!$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} packt den Trank sein$"

Route1_Text_CanJumpFromLedges::
    .string "Fall nicht wenn du runter springst!\p"
    .string "Sonst könntest du dir etwas brechen.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "Alabastia - Vertania City"

Route1_Text_Oak::
    .string "OAK: Oh, my!\p"  
    .string "It seems you caught me during\n"  
    .string "my lunch hour!\p"  
    .string "{PLAYER}, you have truly\n"  
    .string "come into your own!\p"  
    .string "Your POKéMON LEAGUE challenge\n"  
    .string "has reignited a spirit that\l"  
    .string "left me a long time ago…\p"  
    .string "Back in my day, I was a\n"  
    .string "serious TRAINER!\p"  
    .string "How about we spar a bit?\n"  
    .string "What say you?$"

Route1_Text_OakDefeat::
    .string "Hmm…\p"  
    .string "I still have a lot to learn!$" 

Route1_Text_OakPostBattle::
    .string "Well done, {PLAYER}!\p"  
    .string "You've certainly proved your\n"  
    .string "mettle.\p"  
    .string "It seems I might be getting\n"  
    .string "a bit rusty in my old age.\p"  
    .string "A good trainer always strives\n"  
    .string "for improvement, and so shall I.\p"  
    .string "May your journey continue to be\n"  
    .string "one of growth and discovery.$"  
    
Route1_Text_NoOak::
    .string "Maybe some other time!$"  

Route1_Text_YesOak::
    .string "Excellent!\p"  
    .string "Prepare yourself for a\n"  
    .string "real challenge!$"   

 


